Support an additional exporter port
DripEmail/prometheus-ecs-discovery pull request #1
Opened 2019-05-13 15:58 UTC by mnadel

Support an additional exporter port via Docker label PROMETHEUS_EXPORTER_PORT2

2019-05-13 22:40 UTC, masonkmeyer requested changes
@mnadel This doesn't look quite right to me. 

You are reusing the v variable. I think it is always going to be set by the the second call to get docker labels for "PROMETHEUS_EXPORTER_PORT2". 

The result looks like it will only work if you set both labels. I could be wrong. But, it might be worth a look.

2019-05-14 00:52 UTC, liamstewart commented
Can you provide some context on the reason for this change?

2019-05-14 01:04 UTC, mnadel commented
The Shopify Catalog has a homegrown Prometheus exporter that aggregates data into the DB across PIDs and then pulls from there. (Because, at the time, we didn't have a way to use prom_multi_proc in ECS.) I now want to add a new metric and use prom_multi_proc instead of the DB. Since it's already got an exporter, I need to be able to discover a second scrape endpoint in the same service. (This is similar to a technique we use in EC2, being able to specify multiple scrape endpoints per VM.)

2019-05-14 01:06 UTC, mnadel commented
i.e. This is a prereq to https://github.com/DripEmail/drip-service-catalog-shopify/pull/117

2019-05-14 01:07 UTC, saine1a commented
Is that really a good idea ;-)

On Mon, May 13, 2019 at 7:04 PM Michael Nadel <notifications@github.com>
wrote:

> The Shopify Catalog has a homegrown Prometheus exporter that aggregates
> data into the DB across PIDs and then pulls from there. (Because, at the
> time, we didn't have a way to use prom_multi_proc in ECS.) I now want to
> add a new metric and use prom_multi_proc instead of the DB. Since it's
> already got an exporter, I need to be able to discover a second scrape
> endpoint in the same service. (This is similar to a technique we use in
> EC2, being able to specify multiple scrape endpoints per VM.)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DripEmail/prometheus-ecs-discovery/pull/1?email_source=notifications&email_token=ADUUCFSDU63RJC75C6TMGG3PVIFYTA5CNFSM4HMRHG22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVJ642Y#issuecomment-492039787>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADUUCFURAC6ATXIKRMDIP4TPVIFYTANCNFSM4HMRHG2Q>
> .
>

2019-05-14 01:16 UTC, mnadel commented
@liamstewart We want to be able to run multiple exporters per container; e.g. https://github.com/atongen/prom_multi_proc for app code, and a node exporter. This is a pattern use use for EC2 for these two use cases.

2019-05-14 13:46 UTC, masonkmeyer reviewed
@mnadel While I believe this code with work, I still have a few remaining concerns for you to consider. 

First, this code still has an issue with temporal coupling. For example, you can't set _PROMETHEUS_EXPORTER_PORT2_ without setting _PROMETHEUS_EXPORTER_PORT_. This seems a little awkward. I could see a scenario where a developer refactors a terraform file and removes a label without realizing it has a numeric suffix. It requires the end user to know a little too much about how this code is implemented for it to work correctly. 

Second, the "numeric suffix" is a code smell that I try to avoid. Although unlikely, most developers might assume that __PROMETHEUS_EXPORTER_PORT3_ would work or that _PROMETHEUS_EXPORTER_PORT1_ would work. 

I would consider taking Docker's advice on [structured label values](https://docs.docker.com/config/labels-custom-metadata/). It seems to me a comma separated list would solve these issues and keep backwards compatibility. It also reduces some of the duplicate code logic when you treat the ports as a slice.

2019-05-14 14:16 UTC, atongen reviewed
I think I agree that a csv feels a little better in this case.

Also, if we fork this, do we intend to try to get the changes merged upstream? If not then it could become a maintenance headache at some point in the future.

2019-05-14 14:30 UTC, mnadel commented
CSV makes sense, thanks @masonkmeyer.

They introduced changes addressing the reasons we forked in the first place, but that require changes to how we're using it. It's a small enough project that I'm not concerned about diverging from upstream at the moment.

2019-05-14 14:53 UTC, liamstewart commented
Agree with comma-separated values.

Is there anything preventing switching the existing metrics to prom_multi_proc first? If not, will the metrics endpoint in the catalog server be removed and replaced in a follow-up?

What is the expected cardinality of the account label on the metric? Putting account-type information in metrics is always questionable, though it can be reasonable in certain cases. Logs would be better for this, I think - is the catalog server hooked up to cloudwatch logs?

2019-05-14 14:56 UTC, mnadel commented
All goos points @liamstewart. I don't have bandwidth to retrofit existing metrics, but CloudWatch + Log Insights would probably be a good way to answer the questions I have.

2025-11-21 15:00 UTC, tayjohno commented
7 years stale. I'm closing this. We clearly didn't need it _too_ badly.

2025-11-21 15:00 UTC, closed without merging

2025-11-23 00:23 UTC, mnadel commented
> 7 years stale. I'm closing this. We clearly didn't need it _too_ badly.

fiiiiine